In [2]:
import pandas as pd
import numpy as np
%matplotlib inline
from pathlib import Path
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [2]:
#loading the file
us_weather_df = pd.read_csv("C:/Users/zhaoy/Documents/ECON_611_Uniper_Project/ECON-611-Uniper-Project/data_files/Monthly_data/US_weather_data/combined_us_weather.csv")
ca_weather_df = pd.read_csv("C:/Users/zhaoy/Documents/ECON_611_Uniper_Project/ECON-611-Uniper-Project/data_files/Monthly_data/CA_weather_data/combined_ca_weather.csv", encoding='ISO-8859-1')
ab_weather_df = pd.read_csv("C:/Users/zhaoy/Documents/ECON_611_Uniper_Project/ECON-611-Uniper-Project/data_files/monthly_data/CA_weather_data/alberta_weather.csv", encoding='ISO-8859-1')

In [3]:
monthly_df = pd.read_csv("C:/Users/zhaoy/Documents/ECON_611_Uniper_Project/ECON-611-Uniper-Project/data_files/Monthly_data/Monthly_data.csv")

In [5]:
monthly_df.isnull().sum()

DATE                                     0
CA_Inflation                             1
All-items excluding food and energy 7    0
US_CPI                                   0
US_Interest_Rate                         0
CA_Interest_rate                         0
WCS_US                                   1
WTI_US                                   1
CADUSD                                   0
WTI (CAD/bbl)                            0
Edmonton Light (CAD/bbl)                 0
WCS (CAD/bbl)                            0
LLS (CAD/bbl)                            0
Brent (CAD/bbl)                          0
Crude Oil - Light                        0
Crude Oil - Medium                       0
Crude Oil - Heavy                        0
Crude Oil - Ultra Heavy                  0
dtype: int64

In [8]:
daily_df = pd.read_csv("C:/Users/zhaoy/Documents/ECON_611_Uniper_Project/ECON-611-Uniper-Project/data_files/Daily_data/Daily_data.csv")
daily_df2 = pd.read_csv("C:/Users/zhaoy/Documents/ECON_611_Uniper_Project/ECON-611-Uniper-Project/data_files/Daily_data/Daily_data(cleaned).csv")

In [7]:
daily_df.isnull().sum()

Date                                                 0
Henry USD/MMBtu                                    365
AECO 5A USD/MMBtu                                  365
AECO 5A Cad/GJ                                     365
Electricity_Daily_Average                            0
Electricity_Daily_On_Peak_Average                    0
Electricity_Daily_Off_Peak_Average                   0
Electricity_30Ravg Average                           0
Electricity_30Ravg_On_Peak_Average                   0
Electricity_30Ravg_ Off_Peak_Average                 0
Measured Receipts Volume (103M3)                    31
NGTL_Storage_Receipts_Volume_(103M3)                31
NGTL_Gordondale_Receipts_Volume_(103M3)             31
NGTL_Groundbirch_East_Receipts_Volume_(103M3)       31
NGTL_Intra_Provincial_Deliveries_Volume_(103M3)     31
NGTL_Border_Deliveries_Volume_(103M3)               31
NGTL_Empress_Deliveries_Volume_(103M3)              31
NGTL_ABC_Deliveries_Volume_(103M3)                  31
NGTL_McNeil_Deliveries_Volume_(103M3)               31
NGTL_Gordondale_Deliveries_Volume_(103M3)           31
NGTL_Storage_Deliveries_Volume_(103M3)              31
dtype: int64

In [10]:
daily_df.describe

<bound method NDFrame.describe of             Date  Henry USD/MMBtu  AECO 5A USD/MMBtu  AECO 5A Cad/GJ  \
0       1/1/2017              NaN                NaN             NaN
1       1/2/2017              NaN                NaN             NaN
2       1/3/2017              NaN                NaN             NaN
3       1/4/2017              NaN                NaN             NaN
4       1/5/2017              NaN                NaN             NaN
...          ...              ...                ...             ...
2551  12/27/2023            2.480             1.2793          1.6009
2552  12/28/2023            2.625             1.3343          1.6700
2553  12/29/2023            2.550             1.3208          1.6531
2554  12/30/2023            2.550             1.3208          1.6531
2555  12/31/2023            2.550             1.3208          1.6531

      Electricity_Daily_Average  Electricity_Daily_On_Peak_Average  \
0                         19.31                              20.85
1                         29.85                              34.20
2                         25.87                              27.42
3                         25.76                              29.11
4                         19.42                              19.78
...                         ...                                ...
2551                      44.51                              32.97
2552                      21.34                              22.84
2553                      66.31                              81.80
2554                      27.07                              28.11
2555                      30.14                              34.47

      Electricity_Daily_Off_Peak_Average  Electricity_30Ravg Average  \
0                                  16.23                       24.31
1                                  21.13                       24.82
2                                  22.77                       25.14
3                                  19.06                       25.42
4                                  18.69                       25.38
...                                  ...                         ...
2551                               67.58                       61.65
2552                               18.36                       60.65
2553                               35.33                       60.77
2554                               24.99                       52.78
2555                               21.48                       52.01

      Electricity_30Ravg_On_Peak_Average  \
0                                  26.57
1                                  27.19
2                                  27.54
3                                  27.89
4                                  27.80
...                                  ...
2551                               72.02
2552                               70.79
2553                               71.08
2554                               61.02
2555                               60.19

      Electricity_30Ravg_ Off_Peak_Average  ...  \
0                                    19.80  ...
1                                    20.07  ...
2                                    20.35  ...
3                                    20.48  ...
4                                    20.55  ...
...                                    ...  ...
2551                                 40.91  ...
2552                                 40.36  ...
2553                                 40.16  ...
2554                                 36.30  ...
2555                                 35.67  ...

      NGTL_Storage_Receipts_Volume_(103M3)  \
0                                  39105.7
1                                  35628.2
2                                  56877.4
3                                  51980.7
4                                  41777.5
...                                    ...
2551                                   NaN
2552                                   NaN
2553                                   NaN
2554                                   NaN
2555                                   NaN

      NGTL_Gordondale_Receipts_Volume_(103M3)  \
0                                      3965.8
1                                      2854.0
2                                      2832.5
3                                      2979.2
4                                      2382.7
...                                       ...
2551                                      NaN
2552                                      NaN
2553                                      NaN
2554                                      NaN
2555                                      NaN

      NGTL_Groundbirch_East_Receipts_Volume_(103M3)  \
0                                           10308.0
1                                           10221.2
2                                           10236.0
3                                            9510.6
4                                            9912.5
...                                             ...
2551                                            NaN
2552                                            NaN
2553                                            NaN
2554                                            NaN
2555                                            NaN

      NGTL_Intra_Provincial_Deliveries_Volume_(103M3)  \
0                                            177681.6
1                                            186470.6
2                                            186598.2
3                                            179125.0
4                                            176935.0
...                                               ...
2551                                              NaN
2552                                              NaN
2553                                              NaN
2554                                              NaN
2555                                              NaN

      NGTL_Border_Deliveries_Volume_(103M3)  \
0                                  191746.8
1                                  189014.8
2                                  191846.2
3                                  196232.9
4                                  198116.7
...                                     ...
2551                                    NaN
2552                                    NaN
2553                                    NaN
2554                                    NaN
2555                                    NaN

      NGTL_Empress_Deliveries_Volume_(103M3)  \
0                                    67435.7
1                                    67325.4
2                                    68786.9
3                                    68613.5
4                                    68541.6
...                                      ...
2551                                     NaN
2552                                     NaN
2553                                     NaN
2554                                     NaN
2555                                     NaN

      NGTL_ABC_Deliveries_Volume_(103M3)  \
0                                65237.7
1                                63451.6
2                                62590.7
3                                64751.8
4                                65225.6
...                                  ...
2551                                 NaN
2552                                 NaN
2553                                 NaN
2554                                 NaN
2555                                 NaN

      NGTL_McNeil_Deliveries_Volume_(103M3)  \
0                                   52237.2
1                                   51766.1
2                                   53418.3
3                                   55354.6
4                                   56139.9
...                                     ...
2551                                    NaN
2552                                    NaN
2553                                    NaN
2554                                    NaN
2555                                    NaN

      NGTL_Gordondale_Deliveries_Volume_(103M3)  \
0                                           0.0
1                                           0.0
2                                           0.0
3                                           0.0
4                                           0.0
...                                         ...
2551                                        NaN
2552                                        NaN
2553                                        NaN
2554                                        NaN
2555                                        NaN

      NGTL_Storage_Deliveries_Volume_(103M3)
0                                      684.7
1                                        0.0
2                                        0.0
3                                      608.6
4                                      643.8
...                                      ...
2551                                     NaN
2552                                     NaN
2553                                     NaN
2554                                     NaN
2555                                     NaN

[2556 rows x 21 columns]>

In [9]:
daily_df2.isnull().sum()

date                                               0
henry_usd/mmbtu                                    0
aeco_5a_usd/mmbtu                                  0
aeco_5a_cad/gj                                     0
electricity_daily_average                          0
electricity_daily_on_peak_average                  0
electricity_daily_off_peak_average                 0
electricity_30ravg_average                         0
electricity_30ravg_on_peak_average                 0
electricity_30ravg__off_peak_average               0
measured_receipts_volume_(103m3)                   0
ngtl_storage_receipts_volume_(103m3)               0
ngtl_gordondale_receipts_volume_(103m3)            0
ngtl_groundbirch_east_receipts_volume_(103m3)      0
ngtl_intra_provincial_deliveries_volume_(103m3)    0
ngtl_border_deliveries_volume_(103m3)              0
ngtl_empress_deliveries_volume_(103m3)             0
ngtl_abc_deliveries_volume_(103m3)                 0
ngtl_mcneil_deliveries_volume_(103m3)              0
ngtl_gordondale_deliveries_volume_(103m3)          0
ngtl_storage_deliveries_volume_(103m3)             0
dtype: int64

In [11]:
daily_df2.describe

<bound method NDFrame.describe of             date  henry_usd/mmbtu  aeco_5a_usd/mmbtu  aeco_5a_cad/gj  \
0     2018-01-01            3.580             2.8248          3.3518
1     2018-01-02            3.580             1.7509          2.0754
2     2018-01-03            6.625             1.5555          1.8480
3     2018-01-04            6.875             1.5478          1.8377
4     2018-01-05            4.420             1.3134          1.5431
...          ...              ...                ...             ...
2155  2023-11-26            2.715             1.9322          2.5153
2156  2023-11-27            2.715             1.8144          2.3449
2157  2023-11-28            2.735             1.9060          2.4505
2158  2023-11-29            2.785             1.8903          2.4360
2159  2023-11-30            2.700             1.8949          2.4403

      electricity_daily_average  electricity_daily_on_peak_average  \
0                         37.12                              35.50
1                         33.27                              33.89
2                         34.03                              35.20
3                         32.83                              34.77
4                         32.65                              34.10
...                         ...                                ...
2155                     106.34                             102.81
2156                      49.04                              44.40
2157                      51.51                              59.85
2158                      62.49                              73.14
2159                     266.94                             329.96

      electricity_daily_off_peak_average  electricity_30ravg_average  \
0                                  40.36                       22.62
1                                  32.05                       22.96
2                                  31.69                       23.44
3                                  28.93                       23.95
4                                  29.76                       24.38
...                                  ...                         ...
2155                              113.40                       91.76
2156                               58.32                       91.54
2157                               34.84                       89.02
2158                               41.19                       86.77
2159                              140.90                       93.88

      electricity_30ravg_on_peak_average  \
0                                  23.69
1                                  24.03
2                                  24.53
3                                  25.09
4                                  25.53
...                                  ...
2155                              101.36
2156                              101.35
2157                               99.98
2158                               96.45
2159                              105.69

      electricity_30ravg__off_peak_average  ...  \
0                                    20.48  ...
1                                    20.82  ...
2                                    21.25  ...
3                                    21.67  ...
4                                    22.06  ...
...                                    ...  ...
2155                                 72.59  ...
2156                                 71.95  ...
2157                                 67.12  ...
2158                                 67.42  ...
2159                                 70.27  ...

      ngtl_storage_receipts_volume_(103m3)  \
0                                  67055.7
1                                  53334.3
2                                  28213.0
3                                  38279.6
4                                  22488.2
...                                    ...
2155                                6569.5
2156                                8955.5
2157                               19439.8
2158                               19277.6
2159                               35370.5

      ngtl_gordondale_receipts_volume_(103m3)  \
0                                      4327.7
1                                      5141.3
2                                      4423.3
3                                      4600.9
4                                      4986.4
...                                       ...
2155                                   3012.4
2156                                   3018.1
2157                                   3003.8
2158                                   3034.2
2159                                   3145.4

      ngtl_groundbirch_east_receipts_volume_(103m3)  \
0                                           12802.6
1                                           12527.0
2                                           11005.8
3                                           12507.9
4                                           13869.0
...                                             ...
2155                                         2479.4
2156                                         3398.0
2157                                         5087.8
2158                                         5073.7
2159                                         3116.1

      ngtl_intra_provincial_deliveries_volume_(103m3)  \
0                                            189057.3
1                                            186041.2
2                                            185875.1
3                                            186013.1
4                                            180811.1
...                                               ...
2155                                         198549.3
2156                                         197237.6
2157                                         191177.7
2158                                         201121.4
2159                                         205210.5

      ngtl_border_deliveries_volume_(103m3)  \
0                                  210629.0
1                                  217517.4
2                                  215146.1
3                                  217082.2
4                                  210544.3
...                                     ...
2155                               215404.6
2156                               212506.3
2157                               238539.0
2158                               240537.1
2159                               238307.9

      ngtl_empress_deliveries_volume_(103m3)  \
0                                    96077.1
1                                   100268.2
2                                    97458.1
3                                    98996.7
4                                    94375.4
...                                      ...
2155                                125546.6
2156                                122333.4
2157                                128295.2
2158                                128294.9
2159                                126615.2

      ngtl_abc_deliveries_volume_(103m3)  \
0                                61914.5
1                                63916.3
2                                64814.9
3                                65416.2
4                                62671.0
...                                  ...
2155                             62565.1
2156                             62618.5
2157                             81195.4
2158                             81570.7
2159                             82263.7

      ngtl_mcneil_deliveries_volume_(103m3)  \
0                                   47056.8
1                                   46709.1
2                                   46160.5
3                                   43285.0
4                                   45130.2
...                                     ...
2155                                17463.9
2156                                17666.2
2157                                19140.5
2158                                19766.8
2159                                18678.8

      ngtl_gordondale_deliveries_volume_(103m3)  \
0                                           0.0
1                                           0.0
2                                           0.0
3                                           0.0
4                                           0.0
...                                         ...
2155                                        0.0
2156                                        0.0
2157                                        0.0
2158                                        0.0
2159                                        0.0

      ngtl_storage_deliveries_volume_(103m3)
0                                        0.0
1                                      706.8
2                                      808.0
3                                      474.8
4                                      777.0
...                                      ...
2155                                  5722.7
2156                                  4170.3
2157                                   162.0
2158                                    32.3
2159                                   166.8

[2160 rows x 21 columns]>

In [3]:
us_weather_df.head()

,NAME,DATE,AWND,PRCP,SNOW,SNWD,TMAX,TMIN
0,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",1/1/2017,2.8,0.0,0.0,0.0,10.0,0.6
1,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",1/2/2017,2.4,0.0,0.0,0.0,6.1,-0.5
2,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",1/3/2017,1.4,0.0,0.0,0.0,10.0,-0.5
3,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",1/4/2017,3.8,0.0,0.0,0.0,13.3,-0.5
4,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",1/5/2017,5.6,0.0,0.0,0.0,13.9,2.2

In [12]:
daily_df.columns=daily_df.columns.str.replace(' ', '_')

In [5]:
daily_df.dtypes

Date                                                object
Henry USD/MMBtu                                    float64
AECO 5A USD/MMBtu                                  float64
AECO 5A Cad/GJ                                     float64
Electricity_Daily_Average                          float64
Electricity_Daily_On_Peak_Average                  float64
Electricity_Daily_Off_Peak_Average                 float64
Electricity_30Ravg Average                         float64
Electricity_30Ravg_On_Peak_Average                 float64
Electricity_30Ravg_ Off_Peak_Average               float64
Measured Receipts Volume (103M3)                   float64
NGTL_Storage_Receipts_Volume_(103M3)               float64
NGTL_Gordondale_Receipts_Volume_(103M3)            float64
NGTL_Groundbirch_East_Receipts_Volume_(103M3)      float64
NGTL_Intra_Provincial_Deliveries_Volume_(103M3)    float64
NGTL_Border_Deliveries_Volume_(103M3)              float64
NGTL_Empress_Deliveries_Volume_(103M3)             float64
NGTL_ABC_Deliveries_Volume_(103M3)                 float64
NGTL_McNeil_Deliveries_Volume_(103M3)              float64
NGTL_Gordondale_Deliveries_Volume_(103M3)          float64
NGTL_Storage_Deliveries_Volume_(103M3)             float64
dtype: object

In [6]:
daily_df['Date'] = pd.to_datetime(daily_df['Date'])

In [13]:
daily_df.dtypes

Date                                               datetime64[ns]
Henry_USD/MMBtu                                           float64
AECO_5A_USD/MMBtu                                         float64
AECO_5A_Cad/GJ                                            float64
Electricity_Daily_Average                                 float64
Electricity_Daily_On_Peak_Average                         float64
Electricity_Daily_Off_Peak_Average                        float64
Electricity_30Ravg_Average                                float64
Electricity_30Ravg_On_Peak_Average                        float64
Electricity_30Ravg__Off_Peak_Average                      float64
Measured_Receipts_Volume_(103M3)                          float64
NGTL_Storage_Receipts_Volume_(103M3)                      float64
NGTL_Gordondale_Receipts_Volume_(103M3)                   float64
NGTL_Groundbirch_East_Receipts_Volume_(103M3)             float64
NGTL_Intra_Provincial_Deliveries_Volume_(103M3)           float64
NGTL_Border_Deliveries_Volume_(103M3)                     float64
NGTL_Empress_Deliveries_Volume_(103M3)                    float64
NGTL_ABC_Deliveries_Volume_(103M3)                        float64
NGTL_McNeil_Deliveries_Volume_(103M3)                     float64
NGTL_Gordondale_Deliveries_Volume_(103M3)                 float64
NGTL_Storage_Deliveries_Volume_(103M3)                    float64
dtype: object

In [14]:
monthly_df.CA_Inflation

AttributeError: 'DataFrame' object has no attribute 'CA_Inflation'

In [18]:
daily_df.head()

,Date,Henry_USD/MMBtu,AECO_5A_USD/MMBtu,AECO_5A_Cad/GJ,Electricity_Daily_Average,Electricity_Daily_On_Peak_Average,Electricity_Daily_Off_Peak_Average,Electricity_30Ravg_Average,Electricity_30Ravg_On_Peak_Average,Electricity_30Ravg__Off_Peak_Average,...,NGTL_Storage_Receipts_Volume_(103M3),NGTL_Gordondale_Receipts_Volume_(103M3),NGTL_Groundbirch_East_Receipts_Volume_(103M3),NGTL_Intra_Provincial_Deliveries_Volume_(103M3),NGTL_Border_Deliveries_Volume_(103M3),NGTL_Empress_Deliveries_Volume_(103M3),NGTL_ABC_Deliveries_Volume_(103M3),NGTL_McNeil_Deliveries_Volume_(103M3),NGTL_Gordondale_Deliveries_Volume_(103M3),NGTL_Storage_Deliveries_Volume_(103M3)
0,2017-01-01,NaN,NaN,NaN,19.31,20.85,16.23,24.31,26.57,19.80,...,39105.7,3965.8,10308.0,177681.6,191746.8,67435.7,65237.7,52237.2,0.0,684.7
1,2017-01-02,NaN,NaN,NaN,29.85,34.20,21.13,24.82,27.19,20.07,...,35628.2,2854.0,10221.2,186470.6,189014.8,67325.4,63451.6,51766.1,0.0,0.0
2,2017-01-03,NaN,NaN,NaN,25.87,27.42,22.77,25.14,27.54,20.35,...,56877.4,2832.5,10236.0,186598.2,191846.2,68786.9,62590.7,53418.3,0.0,0.0
3,2017-01-04,NaN,NaN,NaN,25.76,29.11,19.06,25.42,27.89,20.48,...,51980.7,2979.2,9510.6,179125.0,196232.9,68613.5,64751.8,55354.6,0.0,608.6
4,2017-01-05,NaN,NaN,NaN,19.42,19.78,18.69,25.38,27.80,20.55,...,41777.5,2382.7,9912.5,176935.0,198116.7,68541.6,65225.6,56139.9,0.0,643.8

In [10]:
ca_weather_df.head()

,Station Name,Date/Time,Year,Month,Day,Max Temp (°C),Min Temp (°C),Mean Temp (°C),Heat Deg Days (°C),Cool Deg Days (°C),Total Rain (mm),Total Snow (cm),Total Precip (mm),Snow on Grnd (cm),Dir of Max Gust (10s deg),Spd of Max Gust (km/h)
0,BANFF CS,1/1/2017,2017,1,1,-8.2,-18.4,-13.3,31.3,0.0,NaN,NaN,0.6,14.0,6.0,37
1,BANFF CS,1/2/2017,2017,1,2,-17.3,-31.0,-24.2,42.2,0.0,NaN,NaN,3.3,14.0,NaN,<31
2,BANFF CS,1/3/2017,2017,1,3,-19.3,-36.7,-28.0,46.0,0.0,NaN,NaN,3.2,14.0,NaN,<31
3,BANFF CS,1/4/2017,2017,1,4,-15.2,-31.6,-23.4,41.4,0.0,NaN,NaN,0.3,13.0,NaN,<31
4,BANFF CS,1/5/2017,2017,1,5,-10.2,-15.6,-12.9,30.9,0.0,NaN,NaN,0.0,14.0,NaN,<31

In [11]:
ab_weather_df.head()

,Township,Date,Air Temp. Min. (°C),Air Temp. Max. (°C),Precip. (mm),Precip. Accumulated (mm),Relative Humidity Avg. (%),Modelled Snow Water Equiv. (mm),Incoming Solar Rad. Total (MJ/m2),Modelled Incoming Rad. Total (MJ/m2),Wind Speed 10 m Avg. (km/h)
0,T009R21W4,1/1/2017,-14.94,-4.96,1.30,1.30,89.79,11.12,3.13,3.99,16.73
1,T009R21W4,1/2/2017,-24.37,-13.47,0.27,1.57,85.18,11.42,3.48,4.20,4.36
2,T009R21W4,1/3/2017,-29.41,-17.53,0.26,1.83,80.17,11.71,4.48,4.41,8.67
3,T009R21W4,1/4/2017,-23.66,-10.17,0.27,2.10,81.87,12.01,3.84,4.74,12.36
4,T009R21W4,1/5/2017,-20.93,-4.17,0.26,2.36,74.93,12.29,3.49,5.33,13.27